# Generated by Django 5.1.4 on 2025-02-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherhistory',
            name='soil_ph',
            field=models.DecimalField(decimal_places=2, default=7.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='weatherhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weatherhistory',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='weatherhistory',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='weatherhistory',
            name='location_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherhistory',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='weatherhistory',
            name='precipitation',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='weatherhistory',
            name='soil_moisture',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='weatherhistory',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='weatherhistory',
            name='weather_condition',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weatherhistory',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
